### ISSUE TITLE
Extension always calls SSM Parameter Store

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/newrelic-lambda-extension#191] opened 2024-02-07 03:49 UTC
## Description

The extension always calls SSM Parameter Store, even if Secrets Manager is used for the license key. This results in permissions errors if the lambda doesn't have permission to SSM (which it doesn't actually need in this situation, and shouldn't have). 

The errors create CloudTrail entries and may result in false alarms/unnecessary triage.

## Steps to Reproduce

Install the extension layer, without giving the Lambda role permissions to access SSM. 

Result: many errors in CloudTrail.

## Expected Behavior

No calls to SSM if Secrets Manager has the key.

## Relevant Logs / Console output

```
"errorCode":"AccessDenied","errorMessage":"User: arn:aws:sts::12345:assumed-role/example-region-lambdaRole/my-Lambda is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:region:12345:parameter/NEW_RELIC_LICENSE_KEY because no identity-based policy allows the ssm:GetParameter action"
```

## Your Environment

NR Layer: NewRelicNodeJS18X:55

**Comment by iamemilio** [comment] 2024-02-14 18:19
working on a fix for this in an upcoming release. We will reduce the calls to the SSM store, and allow users to disable calling the SSM store entirely.

**Comment by chaudharysaket** [comment] 2024-04-10 11:03
We have merged the [fix](https://github.com/newrelic/newrelic-lambda-extension/pull/203), waiting for the new layers [workflow](https://github.com/newrelic/newrelic-lambda-layers/pull/220) such that it can be released to the layers.

**Comment by rittneje** [comment] 2024-05-13 14:27
@chaudharysaket Was this fix released?

**Comment by chaudharysaket** [comment] 2024-05-15 14:35
@rittneje We will release all the changes as new layers for each runtime by the end of May. Thank you!

**Comment by nunofernandes** [comment] 2024-06-14 16:52
Hello,

I'm using the following layer arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicPython312:8 and I'm also experiencing the same issue.

I'm not using the secrets manager but I'm using SSM parameter store (with NEW_RELIC_LICENSE_KEY_SSM_PARAMETER_NAME pointing to the correct place where the key resides and the lambda has access to it.

Even so, I'm flooded with logs in cloudtrail:

```
    "errorMessage": "User: arn:aws:sts::12345:assumed-role/bla/bla is not authorized to perform: secretsmanager:GetSecretValue on resource: NEW_RELIC_LICENSE_KEY because no identity-based policy allows the secretsmanager:GetSecretValue action",
```

**Comment by rittneje** [comment] 2024-06-14 17:33
@nunofernandes Here is the latest from New Relic support:

> - New target for release of this feature is 6/21 (end of sprint).
> - This release is also expected to resolve a similar issue involving Secrets Manager calls.

**Comment by chaudharysaket** [comment] 2024-06-21 18:46
We have released extension [v2.3.12](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.3.12) that solves the above issues with unwanted SSM & secrets manager calls. We will release layers [[PR](https://github.com/newrelic/newrelic-lambda-layers/pull/250)] after testing with each runtime - python, nodejs, golang, java & dotnet [6/25].

**Comment by chaudharysaket** [comment] 2024-06-21 19:09
We have r[eleased layers with extension only](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v2.3.12_extension), which are used by golang runtime lambda. We will release other runtime layers as mentioned above.

**Closed** 2024-06-24 03:43 UTC
Labels: bug

**Comment by chaudharysaket** [comment] 2024-06-24 18:47
Hi @rittneje & @nunofernandes
We have released new layers with the updated extension. Please let us know if you still face issue with cloud trail logs due to unnecessary calls to either SSM or secrets manager. 
Thank you!

**Comment by rittneje** [comment] 2024-06-24 22:43
@chaudharysaket From testing we have observed that the offending SSM calls no longer happen with the latest layer versions.

**Comment by nunofernandes** [comment] 2024-06-25 09:24
@chaudharysaket I did the change one hour ago and I can confirm that I can't see anymore those SSM calls being made.. :clap:  :fireworks:
